# Мета-данные, не модифицировать.
# Default: 0
configVersion = 2

[general]

	# Переключает все функции мода.
	# Default: true
	enabled = true
	# Отключите это, чтобы эффекты мода были доступны только для вида от первого лица.
	# Default: true
	enableInThirdPerson = true
	# Чувствительность крена камеры, вызванного поворотом по горизонтали.
	# Default: 1.0
	turningRollAccumulation = 4.0
	# Максимальная сила крена камеры, вызванного поворотом по горизонтали.
	# Default: 1.25
	turningRollIntensity = 3.0
	# Плавность затухания крена камеры, вызванного поворотом по горизонтали.
	# Default: 1.0
	turningRollSmoothing = 2.0
	# Сила плавного случайного раскачивания, которое срабатывает, когда игрок бездействует достаточно долго.
	# Default: 0.6
	cameraSwayIntensity = 1.0
	# Частота плавного случайного раскачивания, которое срабатывает, когда игрок бездействует достаточно долго.
	# Default: 0.16
	cameraSwayFrequency = 1.0
	# Время, которое игрок должен провести в бездействии, прежде чем плавное случайное раскачивание начнёт появляться.
	# Default: 0.15
	cameraSwayFadeInDelay = 5.0
	# Время, необходимое для появления плавного случайного раскачивания после того, как игрок бездействует достаточно долго.
	# Default: 5.0
	cameraSwayFadeInLength = 2.0
	# Время, необходимое для исчезновения плавного случайного раскачивания, когда игрок начинает двигаться после бездействия.
	# Default: 0.75
	cameraSwayFadeOutLength = 0.5
	# Максимальная сила всех эффектов тряски экрана.
	# Default: 2.5
	screenShakesMaxIntensity = 1.5
	# Скорость, с которой меняется направление или колебания тряски экрана.
	# Default: 6.0
	screenShakesMaxFrequency = 10.0
	# Значение [0..1], связанное с силой тряски экрана, вызванной взрывами.
	# Default: 1.0
	explosionTrauma = 2.0
	# Значение [0..1], связанное с силой тряски экрана, вызванной громом от удара молнии.
	# Default: 0.05
	thunderTrauma = 0.5
	# Значение [0..1], связанное с силой тряски экрана, вызванной любыми действиями, при которых игрок размахивает рукой. Рекомендуется оставлять очень низким.
	# Default: 0.03
	handSwingTrauma = 0.0

[walking]

	# Сила крена камеры, вызванной боковым движением или боковой горизонтальной скоростью.
	# Default: 10.0
	strafingRollFactor = 5.0
	# Интенсивность угловых поворотов камеры, вызванных движением вперёд или назад.
	# Default: 7.0
	forwardVelocityPitchFactor = 2.0
	# Интенсивность угловых поворотов камеры, вызванных вертикальной скоростью.
	# Default: 2.5
	verticalVelocityPitchFactor = 3.0
	# Плавность поворота камеры по углу наклона и крену, вызванная горизонтальным перемещением.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 2.0
	# Плавность изменения угла наклона камеры, вызванная вертикальным перемещением.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 2.0

[swimming]

	# Сила крена камеры, вызванной боковым движением или боковой горизонтальной скоростью.
	# Default: -30.0
	strafingRollFactor = -5.0
	# Интенсивность угловых поворотов камеры, вызванных движением вперёд или назад.
	# Default: 21.0
	forwardVelocityPitchFactor = 2.0
	# Интенсивность угловых поворотов камеры, вызванных вертикальной скоростью.
	# Default: 7.5
	verticalVelocityPitchFactor = 2.0
	# Плавность поворота камеры по углу наклона и крену, вызванная горизонтальным перемещением.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 4.0
	# Плавность изменения угла наклона камеры, вызванная вертикальным перемещением.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 4.0

[flying]

	# Сила крена камеры, вызванной боковым движением или боковой горизонтальной скоростью.
	# Default: -10.0
	strafingRollFactor = -5.0
	# Интенсивность угловых поворотов камеры, вызванных движением вперёд или назад.
	# Default: 7.0
	forwardVelocityPitchFactor = 2.0
	# Интенсивность угловых поворотов камеры, вызванных вертикальной скоростью.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.0
	# Плавность поворота камеры по углу наклона и крену, вызванная горизонтальным перемещением.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 3.0
	# Плавность изменения угла наклона камеры, вызванная вертикальным перемещением.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 3.0

[mounts]

	# Сила крена камеры, вызванной боковым движением или боковой горизонтальной скоростью.
	# Default: 20.0
	strafingRollFactor = 5.0
	# Интенсивность угловых поворотов камеры, вызванных движением вперёд или назад.
	# Default: 7.0
	forwardVelocityPitchFactor = 2.0
	# Интенсивность угловых поворотов камеры, вызванных вертикальной скоростью.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.0
	# Плавность поворота камеры по углу наклона и крену, вызванная горизонтальным перемещением.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 2.0
	# Плавность изменения угла наклона камеры, вызванная вертикальным перемещением.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 2.0

[vehicles]

	# Сила крена камеры, вызванной боковым движением или боковой горизонтальной скоростью.
	# Default: 5.0
	strafingRollFactor = 2.0
	# Интенсивность угловых поворотов камеры, вызванных движением вперёд или назад.
	# Default: 1.75
	forwardVelocityPitchFactor = 1.0
	# Интенсивность угловых поворотов камеры, вызванных вертикальной скоростью.
	# Default: 5.0
	verticalVelocityPitchFactor = 1.0
	# Плавность поворота камеры по углу наклона и крену, вызванная горизонтальным перемещением.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 2.0
	# Плавность изменения угла наклона камеры, вызванная вертикальным перемещением.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 2.0
